### ISSUE TITLE
Literate clean

### ISSUE THREAD

**Issue by dopefishh** [timjs/atom-language-clean#5]
Literate clean does not exist and the `.tcl` extension is already used by `tcl/tk` scripts which causes confusion.

I would propose the `.licl` and `.ldcl` extension in the same fashion as Haskell`s literate files. But first I would like to see an actual delitter.

**Comment by timjs** [comment]
The extension of literate Clean files is `.lcl` not `.tcl`, so no clashes wit Tcl/Tk exist. It contains both *declarations* and *implementations*, which is exactly the purpose of it. Lines preceded with `>> ` are exported in generated `.dcl` files, files preceded with `>  ` (mind the double space) are implementation only.

Support for unliterating and building `.lcl` files can be found in [cl](https://github.com/timjs/cl) (old Go-based implementation can be found at [cl-go](https://github.com/timjs/cl-go)).
